### ISSUE TITLE
Umbrella issues for data3d Addon tasks / bugs

### ISSUE THREAD

**Issue by Aadjou** [archilogic-com/data3d-blender-io#8]
Open issues - ** transfered from https://github.com/archilogic-com/services/issues/41**

# WIP

Import
- [ ] Clean Mesh & use_image_search optional @(low priority)@  
- [ ] Do we have object-specific metadata (-> check with tomas about visibility attribute)?
- [ ] clean mesh / clean hierarchy > improve performance (because of bpy.ops use)
- [ ] Meshes with no uvs that are merged with meshes with uvs: handle unwrapping / disable merge / mark faces (now we generate additional, faulty uv data because of auto uvs when merging)
- [ ] Option to disable coords distinct, remove doubles, tris to quads for previews
- [ ] Reset logger config / remove global variables from addon (eg. the reference to the buffered file)
- [ ]  Improve buffer import performance (parsing data is much slower then json parsing -> data3d importer issue 
- [ ] [convert_tris_to_quads breaks normals](https://github.com/archilogic-com/data3d-blender-io/issues/17)

Export
- [ ] if UV channel does not conform the name, take the channel by index (0 -> uvMap, 1-> uvLightmap else no UV)
- [ ] Material Texture Scale for 3d artists
- [ ]  export hierarchy instead of flattened @(low priority)@ (only for data3d.json)
- [ ]  Apply world matrix from operator params or remove
- [ ] export = import = client (sustainability)
- [ ] Don't export uv's if uv area is 0
- [ ] texture references to texture directory!

General
- [ ] Implement material-cycles / cycles-blender converter service for 3d artists (with restrictions, and only for 3d artists) @(low priority)@
- [ ]  Implement toggle cycles-blender render- done
- [ ] Implement a convert to cycles method for 3d artists

**Comment by ghost** [comment]
gotta go through this tuff an see what is done already sometime
